### ISSUE TITLE
Kotlin 1.5.0 Migration

### ISSUE THREAD

**Issue by utybo** [EpiLink/EpiLink#268]
A ton of really cool stuff is landing with Kotlin 1.5.0

### Requirements

- [x] Non-RC Kotlin 1.5.0 release

### TODO

Running down the [changelog for the RC](https://blog.jetbrains.com/kotlin/2021/04/kotlin-1-5-0-rc-released/), we need to check the following to modernize the code base:

- [x] Unsigned integers. Probably not all that useful for us atm.
- [ ] Stable NIO Path extensions
- [ ] Deprecation of toUpperCase/toLowerCase/toTitleCase (didn't even know the last one existed) -> uppercase/lowercase/titlecase, same with the Char versions, due to locale-sensitive nature of the former. The latter is completely case insensitive.
- [ ] firstNotNullOf() and firstNotNullOfOrNull() on collections, I believe I made a custom extension for this somewhere in EpiLink
- [ ] New assertions in `kotlin-test` that could probably used in the tests
