### ISSUE TITLE
[Epic] CII Best Practices report

### ISSUE THREAD

**Issue by utybo** [EpiLink/EpiLink#293]
Recently used the self-certification tool to check how good (or bad) we're doing things for EpiLink. Turns out, we're pretty alright, but some obvious flaws can be easily fixed.

**This is a huge issue ticket. Points raised here will be gradually fixed.**

Here's the badge. Click on it to see the report on the CII Best Practices website.

[![CII Best Practices](https://bestpractices.coreinfrastructure.org/projects/5097/badge)](https://bestpractices.coreinfrastructure.org/projects/5097)

### Actionable

And here are the things we need to fix to achieve the "passing" level criteria:

- [x] #294
    - "The project website MUST provide information on how to: obtain, provide feedback (as bug reports or enhancements), and contribute to the software."
- [ ] #295
    - "The information on how to contribute SHOULD include the requirements for acceptable contributions (e.g., a reference to any required coding standard). (URL required)"
- [x] #310
    - "To enable collaborative review, the project's source repository MUST include interim versions for review between releases; it MUST NOT include only final releases."
    - We're not doing beta versions right now. We *should* be doing beta/pre-release versions.
- [x] #308
    - "The project MUST publish the process for reporting vulnerabilities on the project site. (URL required)"
    - I don't think we even have a process for this other than "hit us up"
- [x] #300
    - "The project MUST enable one or more compiler warning flags, a "safe" language mode, or use a separate "linter" tool to look for code quality errors or common simple mistakes, if there is at least one FLOSS tool that can implement this criterion in the selected language."
    - Kotlin does not have additional compiler warning flags that may be enabled, so I don't know how this applies. While we use IntelliJ, which provides linting capabilities, this is not codified anywhere.
    - Nothing is done on the JS side of things for this (cc @Litarvan)
- [x] #301
    - "The project MUST address warnings."
    - We don't report them in the first place, so we'll see this later.
- [x] #297
    - "At least one static code analysis tool (beyond compiler warnings and "safe" language modes) MUST be applied to any proposed major production release of the software before its release, if there is at least one FLOSS tool that implements this criterion in the selected language."
    - Kotlin: ~~KtLint~~ Detekt is a great tool for this, but the code base is not clean enough to get meaningful warnings (we would get a lot of warnings about classes being too large). This can be done, but a lot of stuff needs to be configured.
    - JavaScript: No idea, cc @Litarvan
- [x] #298
    - "All medium and higher severity exploitable vulnerabilities discovered with static code analysis MUST be fixed in a timely way after they are confirmed."
    - None are found right now, and any vulnerability for this would be caught in CI and block contributinos, forcing them to be fixed.

### Won't fix

The following cannot be fixed.

- [ ] `know_secure_design` "The project MUST have at least one primary developer who knows how to design secure software. (See ‘details’ for the exact requirements.)"
    - While both @Litarvan and I know about secure software, we have not received (formal) training on it. As such, we do not match the given requirements.
- [ ] `know_common_errors` "At least one of the project's primary developers MUST know of common kinds of errors that lead to vulnerabilities in this kind of software, as well as at least one method to counter or mitigate each of them."
   - Same as above

### Additional suggestions

While the following are not "failures" per se, they should be improved upon:

- [ ] `test_most` "It is SUGGESTED that the test suite cover most (or ideally all) the code branches, input fields, and functionality."
- [ ] `tests_documented_added` "It is SUGGESTED that this policy on adding tests (see test_policy) be documented in the instructions for change proposals."
- [x] #302
    - "It is SUGGESTED that projects be maximally strict with warnings in the software produced by the project, where practical."
- [x] `static_analysis_common_vulnerabilities` "It is SUGGESTED that at least one of the static analysis tools used for the static_analysis criterion include rules or approaches to look for common vulnerabilities in the analyzed language or environment."
    - Static analysis is not met in the first place.
    - Kotlin: I believe ~~KtLint~~ Detekt does that and should be configured to include those reports.
    - JavaScript: Once again, no idea, cc @Litarvan .
- [x] `static_analysis_often` "It is SUGGESTED that static source code analysis occur on every commit or at least daily."
    - CI will do this on every commit, it's just that no analysis is here in the first place.
- [ ] `dynamic_analysis` "It is SUGGESTED that at least one dynamic analysis tool be applied to any proposed major production release of the software before its release."
- [ ] `dynamic_analysis_enable_assertions` "It is SUGGESTED that the project use a configuration for at least some dynamic analysis (such as testing or fuzzing) which enables many assertions. In many cases these assertions should not be enabled in production builds."

---

### Epic information

- **Close if:** Passing badge is earned
- **Priority:** Low
