### ISSUE TITLE
Java 17 upgrade

### ISSUE THREAD

**Issue by utybo** [EpiLink/EpiLink#307]
Java 17 is the new LTS, we need to migrate to it.

### Blocked by

- [x] Gradle does not support Java 17 yet (will come in Gradle 7.3)
- [x] The Kotlin Gradle plugin does not support Java 17 as a target JDK yet (will come in Kotlin 1.6)

### TODO

- [ ] Update dockerfiles
- [ ] Update build files
- [ ] Update CI/CD
