### ISSUE TITLE
[EPIC] EpiLink, the reboot

### ISSUE THREAD

**Issue by utybo** [EpiLink/EpiLink#342]
Aka let's dust off this project!

Hello again! Lots of things have changed since the creation of EpiLink 3 years ago (damn!). This issue is a list of things that need to be done in order to properly reboot this project.

Note that, in its current form, EpiLink still works! You can grab the latest version on Docker as usual. The documentation website  is available [here](https://epilink.zoroark.guru/).

Here is a list of tasks and issues that need to be addressed:

### XL tasks

- [ ] #343
  - EpiLink is a home-made hodgepodge of various Kotlin libraries. In those 3 years, I learned a lot more about Kotlin, its ecosystem and (obviously back-end development). Tegral is a personal framework of mine that combines most of the technologies found in EpiLink in a (somewhat) more evolved form. This will be a good opportunity to also further complete Tegral's featureset by ensuring it can be used with a medium-size project.
  - This supersedes:
    - #322 (migration to Tegral DI instead)
    - #318 (migration to Tegral Config with integrated Hoplite instead)
    - #304 (Tegral can be configured with both TOML and YAML through Hoplite)

- [ ] Review project architecture (supersedes #313)

- [ ] Properly reorganize the project in a Controller - Service - Repository (supersedes #272)
  - Fun fact, I made this project's back-end before knowing about n-tier architecture. Turns out, it's pretty useful

- [ ] Test code refactoring in some way (#255)

### L tasks

- [ ] #275, switch to Docusaurus **Low priority**
- [ ] Update all dependencies
- [ ] Switch OpenAPI documentation to Tegral OpenAPI instead of a manually-created YAML file.
- [ ] Add Liquibase

### M tasks

- [ ] Backlog cleanup
- [ ] #258 
- [ ] #257 and potentially other changes
- [ ] Front-end dependencies update
- [ ] Replace `locations` with `resources` in Ktor

### S tasks

- [ ] #281

**Comment by utybo** [comment]
@Litarvan Feel free to add front-end related things
