### ISSUE TITLE
Frontend page access control

### ISSUE THREAD

**Issue by Litarvan** [EpiLink/EpiLink#45]
Currently, user can access some pages he should not be able to, without being redirected. 

# To-do fixes list
- [x] Redirect from / to the current linking step page
- [ ] Redirect from /auth/:service to the current linking step page
- [ ] Redirect from /home to /profile when the user is logged
