### ISSUE TITLE
Replace hardcoded/missing texts by backend calls/environment variables

### ISSUE THREAD

**Issue by Litarvan** [EpiLink/EpiLink#66]
A lot of texts or links (for example the privacy policy or the sources URL) are hardcoded on the frontend or simply missing. 

# To-do

- [x] Add the ToS page and retrieve it from the backend
- [x] Add the privacy policy page and retrieve it from the backend
- [x] Add the about page with instance information retrieved them from the backend
- [x] Retrieve the backend URL from the environment
- [x] Retrieve the identity prompt text from the backend
- [x] ~~Retrieve the sources URL from the backend or the environment~~ Will eventually be replaced by #82
